#!/usr/bin/env python3
"""
Local SBOM generation script.
Run this to generate SBOMs without waiting for CI/CD.

Usage:
    python security/supply_chain/generate_sbom.py
"""

import json
import sys
import subprocess
from datetime import datetime
from pathlib import Path


def run_command(cmd):
    """Run a shell command and return output."""
    try:
        result = subprocess.run(cmd, shell=True, capture_output=True, text=True)
        return result.returncode, result.stdout, result.stderr
    except Exception as e:
        print(f"Error running command: {e}")
        return 1, "", str(e)


def generate_sbom():
    """Generate SBOM in multiple formats."""
    sbom_dir = Path("security/supply_chain")
    sbom_dir.mkdir(parents=True, exist_ok=True)

    print("🔄 Generating SBOM...\n")

    # Check dependencies
    print("📦 Checking for required tools...")
    tools = ["cyclonedx-bom", "pip"]

    for tool in tools:
        code, _, err = run_command(f"which {tool}")
        if code != 0:
            print(f"❌ {tool} not found. Install with: pip install cyclonedx-bom")
            return False

    print("✓ All tools available\n")

    # Generate CycloneDX SBOM (JSON)
    print("📝 Generating CycloneDX SBOM (JSON)...")
    code, _, err = run_command("cyclonedx-bom -o security/supply_chain/sbom.json -format json")
    if code == 0:
        print("✓ Generated: security/supply_chain/sbom.json")
    else:
        print(f"❌ Failed to generate JSON SBOM: {err}")

    # Generate CycloneDX SBOM (XML)
    print("📝 Generating CycloneDX SBOM (XML)...")
    code, _, err = run_command("cyclonedx-bom -o security/supply_chain/sbom.xml -format xml")
    if code == 0:
        print("✓ Generated: security/supply_chain/sbom.xml")
    else:
        print(f"❌ Failed to generate XML SBOM: {err}")

    # Generate pip list as JSON
    print("📋 Generating installed packages list...")
    code, stdout, _ = run_command("pip list --format=json")
    if code == 0:
        with open(sbom_dir / "installed_packages.json", "w") as f:
            f.write(stdout)
        print("✓ Generated: security/supply_chain/installed_packages.json")

    # Generate markdown report
    print("📄 Generating markdown SBOM report...")
    with open("requirements.txt") as f:
        reqs = [line.strip() for line in f if line.strip() and not line.startswith("#")]

    with open(sbom_dir / "SBOM.md", "w") as out:
        out.write("# Software Bill of Materials (SBOM)\n\n")
        out.write("> Auto-generated by supply chain security script\n\n")
        out.write(f"**Generated**: {datetime.now().isoformat()}\n\n")
        out.write(f"**Total Dependencies**: {len(reqs)}\n\n")

        out.write("## Core Dependencies\n\n")
        for req in reqs:
            if "==" in req:
                name, version = req.split("==")
                out.write(f"- **{name.strip()}** `{version.strip()}`\n")
            elif ">=" in req:
                name, version = req.split(">=")
                out.write(f"- **{name.strip()}** `>={version.strip()}`\n")
            else:
                out.write(f"- **{req}**\n")

        out.write("\n## SBOM Formats Available\n\n")
        out.write("- CycloneDX JSON: `sbom.json`\n")
        out.write("- CycloneDX XML: `sbom.xml`\n")
        out.write("- Pip Packages: `installed_packages.json`\n")

    print("✓ Generated: security/supply_chain/SBOM.md")

    # Run vulnerability scan
    print("\n🔍 Running vulnerability audit...")
    code, stdout, _ = run_command("pip-audit --desc")
    if code == 0:
        print("✓ No vulnerabilities found!")
        print("\nVulnerability Scan Output:")
        print(stdout)
    else:
        print("⚠️  Potential vulnerabilities detected. Review above output.")
        if stdout:
            print(stdout)

    print("\n✅ SBOM generation complete!\n")
    print("📁 Files generated in: security/supply_chain/")
    print("   - sbom.json (CycloneDX)")
    print("   - sbom.xml (CycloneDX)")
    print("   - SBOM.md (Markdown)")
    print("   - installed_packages.json (Pip)")

    return True


if __name__ == "__main__":
    try:
        success = generate_sbom()
        sys.exit(0 if success else 1)
    except KeyboardInterrupt:
        print("\n\n⚠️  Interrupted by user")
        sys.exit(1)
